"use client";

import { useEffect, useState } from "react";
import { format } from "date-fns";

interface Service {
  serviceType: string;
  amountCents: number;
}

interface Agent {
  agentId: string;
  firstName: string;
  lastName: string;
  email: string;
  brokerageName: string;
  services: Service[];
}

export default function QuoteSheetPage({ params }: { params: { agentId: string } }) {
  const [agent, setAgent] = useState<Agent | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const fetchPricing = async () => {
      try {
        const res = await fetch("/api/tc/pricing");

        if (!res.ok) throw new Error("Failed to fetch pricing");

        const data = await res.json();
        const foundAgent = data.agents?.find(
          (a: Agent) => a.agentId === params.agentId
        );

        if (!foundAgent) throw new Error("Agent not found");

        setAgent(foundAgent);
      } catch (err) {
        setError(err instanceof Error ? err.message : "Unknown error");
      } finally {
        setLoading(false);
      }
    };

    fetchPricing();
  }, [params.agentId]);

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <p>Loading quote sheet...</p>
      </div>
    );
  }

  if (error || !agent) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <p className="text-red-600">Error: {error || "Agent not found"}</p>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-white p-8 print:p-0">
      <div className="max-w-3xl mx-auto">
        {/* Header */}
        <div className="mb-8 pb-8 border-b-2 border-gray-300 print:border-b-1">
          <h1 className="text-3xl font-bold text-gray-900 mb-2">QUOTE SHEET</h1>
          <p className="text-gray-600 text-sm">
            Generated on {format(new Date(), "MMMM d, yyyy")}
          </p>
        </div>

        {/* Agent Information */}
        <div className="mb-8 p-6 bg-gray-50 rounded-lg">
          <h2 className="text-lg font-semibold text-gray-900 mb-4">Agent Information</h2>
          <div className="grid grid-cols-2 gap-4">
            <div>
              <p className="text-xs text-gray-500 uppercase tracking-wide">Agent Name</p>
              <p className="text-lg font-medium text-gray-900">
                {agent.firstName} {agent.lastName}
              </p>
            </div>
            <div>
              <p className="text-xs text-gray-500 uppercase tracking-wide">Email</p>
              <p className="text-lg font-medium text-gray-900">{agent.email}</p>
            </div>
            <div className="col-span-2">
              <p className="text-xs text-gray-500 uppercase tracking-wide">Brokerage</p>
              <p className="text-lg font-medium text-gray-900">
                {agent.brokerageName}
              </p>
            </div>
          </div>
        </div>

        {/* Pricing Table */}
        <div className="mb-12">
          <h2 className="text-lg font-semibold text-gray-900 mb-4">Service Pricing</h2>
          <div className="border border-gray-300 rounded-lg overflow-hidden">
            <table className="w-full">
              <thead>
                <tr className="bg-gray-900 text-white">
                  <th className="px-6 py-3 text-left text-sm font-semibold">
                    Service Type
                  </th>
                  <th className="px-6 py-3 text-right text-sm font-semibold">
                    Price
                  </th>
                </tr>
              </thead>
              <tbody>
                {agent.services.map((service, index) => (
                  <tr
                    key={service.serviceType}
                    className={index % 2 === 0 ? "bg-white" : "bg-gray-50"}
                  >
                    <td className="px-6 py-4 text-sm font-medium text-gray-900">
                      {service.serviceType}
                    </td>
                    <td className="px-6 py-4 text-right text-sm font-semibold text-gray-900">
                      ${(service.amountCents / 100).toFixed(2)}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        {/* Footer */}
        <div className="mt-12 pt-8 border-t-2 border-gray-300 text-center text-xs text-gray-600">
          <p>This quote sheet is valid for 30 days from the date shown above.</p>
          <p className="mt-2">For questions or to request a quote, please contact the agent.</p>
          <p className="mt-4 text-gray-400">
            Generated by SignPost Field Pricing System
          </p>
        </div>

        {/* Print Button */}
        <div className="mt-8 text-center print:hidden">
          <button
            onClick={() => window.print()}
            className="px-6 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 font-medium"
          >
            🖨️ Print or Save as PDF
          </button>
          <button
            onClick={() => window.close()}
            className="ml-4 px-6 py-2 bg-gray-200 text-gray-800 rounded-lg hover:bg-gray-300 font-medium"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
}
